import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

import { HiDotsVertical } from "react-icons/hi";
import { IoMdFolder } from "react-icons/io";
import newDoc from "../assets/newDoc.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google_Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* NEW DOCUMENT SECTION */}
      <section className="bg-gray-100 shadow-md px-10 pb-10">
        <div className="xl:max-w-4xl mx-auto">
          <div className="py-6 flex items-center justify-between">
            <h2 className="text-gray-700 text-lg ml-8">Start a new document</h2>
            <div className="p-2 md:p-3 hover:bg-gray-200 hover:transition-all rounded-full cursor-pointer">
              <HiDotsVertical className="text-xl" />
            </div>
          </div>
          <div>
            <Image
              src={newDoc}
              alt="New document"
              width={200}
              height={200}
              className="hover:scale-95 hover:transition-all cursor-pointer"
            />
            <p className="ml-8">Blank</p>
          </div>
        </div>
      </section>

      <section>
        <div className="px-10 xl:px-0 xl:max-w-4xl mx-auto py-8">
          <table className="w-full">
            <tr className="flex items-center justify-between bg-gray-300 p-2 text-sm md:text-lg">
              <th className="font-normal">My Documents</th>
              <th className="font-normal ml-10 lg:ml-60 xl:ml-80">
                Date Created
              </th>
              <th>
                <IoMdFolder name="folder " className="text-2xl" />
              </th>
            </tr>
          </table>
        </div>
      </section>
    </div>
  );
}
